import { Epilogue, Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"],
});

export const epilogue = Epilogue({
  weight: ["500", "600", "800", "900"],
});

export const metadata = {
  title: "Hero Kidz Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <header className="py-2 md:w-11/12 mx-auto">
          <Navbar />
        </header>
        <main className="py-2 md:w-11/12 mx-auto">{children}</main>
      </body>
    </html>
  );
}
